development:
  database: primary
  store_options:
    max_size: <%= 256.megabytes %>
    namespace: development

test:
  database: primary
  store_options:
    max_size: <%= 256.megabytes %>
    namespace: test

production:
  database: primary
  store_options:
    max_size: <%= 256.megabytes %>
    namespace: production
