/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/activities": {
    /** Index activity */
    get: operations["index_api_v1_activities"];
    /** Create activity */
    post: operations["create_api_v1_activities"];
  };
  "/activities/{id}": {
    /** Show activity */
    get: operations["show_api_v1_activities"];
    /** Update activity */
    put: operations["update_api_v1_activities"];
    /** Destroy activity */
    delete: operations["destroy_api_v1_activities"];
    /** Update activity */
    patch: operations["update_api_v1_activities"];
  };
  "/ai/settings": {
    /** Settings ai */
    get: operations["settings_api_v1_ai"];
    /** Update settings ai */
    patch: operations["update_settings_api_v1_ai"];
  };
  "/ai/test_connection": {
    /** Test connection ai */
    post: operations["test_connection_api_v1_ai"];
  };
  "/api_tokens": {
    /** Index api token */
    get: operations["index_api_v1_api_tokens"];
    /** Create api token */
    post: operations["create_api_v1_api_tokens"];
  };
  "/api_tokens/{id}": {
    /** Destroy api token */
    delete: operations["destroy_api_v1_api_tokens"];
  };
  "/auth/login": {
    /** Log in and receive a session token */
    post: operations["login_api_v1_auth"];
  };
  "/auth/logout": {
    /** Revoke the current session */
    delete: operations["logout_api_v1_auth"];
  };
  "/auth/me": {
    /** Current user, account and memberships */
    get: operations["me_api_v1_auth"];
  };
  "/auth/providers": {
    /** Providers auth */
    get: operations["providers_api_v1_auth"];
  };
  "/auth/signup": {
    /** Sign up with email, password and workspace name */
    post: operations["signup_api_v1_auth"];
  };
  "/auth/switch_account": {
    /** Switch the session's current workspace */
    post: operations["switch_account_api_v1_auth"];
  };
  "/automations": {
    /** Index automation */
    get: operations["index_api_v1_automations"];
    /** Create automation */
    post: operations["create_api_v1_automations"];
  };
  "/automations/templates": {
    /** Templates automation */
    get: operations["templates_api_v1_automations"];
  };
  "/automations/{id}": {
    /** Show automation */
    get: operations["show_api_v1_automations"];
    /** Update automation */
    put: operations["update_api_v1_automations"];
    /** Destroy automation */
    delete: operations["destroy_api_v1_automations"];
    /** Update automation */
    patch: operations["update_api_v1_automations"];
  };
  "/automations/{id}/runs": {
    /** Runs automation */
    get: operations["runs_api_v1_automations"];
  };
  "/automations/{id}/toggle": {
    /** Toggle automation */
    post: operations["toggle_api_v1_automations"];
  };
  "/companies": {
    /** Index company */
    get: operations["index_api_v1_companies"];
    /** Create company */
    post: operations["create_api_v1_companies"];
  };
  "/companies/{company_id}/tags": {
    /** Index company tag */
    get: operations["index_api_v1_company_tags"];
    /** Create company tag */
    post: operations["create_api_v1_company_tags"];
  };
  "/companies/{company_id}/tags/{id}": {
    /** Destroy company tag */
    delete: operations["destroy_api_v1_company_tags"];
  };
  "/companies/{id}": {
    /** Show company */
    get: operations["show_api_v1_companies"];
    /** Update company */
    put: operations["update_api_v1_companies"];
    /** Destroy company */
    delete: operations["destroy_api_v1_companies"];
    /** Update company */
    patch: operations["update_api_v1_companies"];
  };
  "/contacts": {
    /** Index contact */
    get: operations["index_api_v1_contacts"];
    /** Create contact */
    post: operations["create_api_v1_contacts"];
  };
  "/contacts/import": {
    /** Import contact */
    post: operations["import_api_v1_contacts"];
  };
  "/contacts/{contact_id}/tags": {
    /** Index contact tag */
    get: operations["index_api_v1_contact_tags"];
    /** Create contact tag */
    post: operations["create_api_v1_contact_tags"];
  };
  "/contacts/{contact_id}/tags/{id}": {
    /** Destroy contact tag */
    delete: operations["destroy_api_v1_contact_tags"];
  };
  "/contacts/{id}": {
    /** Show contact */
    get: operations["show_api_v1_contacts"];
    /** Update contact */
    put: operations["update_api_v1_contacts"];
    /** Destroy contact */
    delete: operations["destroy_api_v1_contacts"];
    /** Update contact */
    patch: operations["update_api_v1_contacts"];
  };
  "/contacts/{id}/erase": {
    /** Erase contact */
    delete: operations["erase_api_v1_contacts"];
  };
  "/contacts/{id}/export": {
    /** Export contact */
    get: operations["export_api_v1_contacts"];
  };
  "/contacts/{id}/score": {
    /** Score contact */
    post: operations["score_api_v1_contacts"];
  };
  "/custom_field_definitions": {
    /** Index custom field definition */
    get: operations["index_api_v1_custom_field_definitions"];
    /** Create custom field definition */
    post: operations["create_api_v1_custom_field_definitions"];
  };
  "/custom_field_definitions/{id}": {
    /** Show custom field definition */
    get: operations["show_api_v1_custom_field_definitions"];
    /** Update custom field definition */
    put: operations["update_api_v1_custom_field_definitions"];
    /** Destroy custom field definition */
    delete: operations["destroy_api_v1_custom_field_definitions"];
    /** Update custom field definition */
    patch: operations["update_api_v1_custom_field_definitions"];
  };
  "/custom_object_definitions": {
    /** Index custom object definition */
    get: operations["index_api_v1_custom_object_definitions"];
    /** Create custom object definition */
    post: operations["create_api_v1_custom_object_definitions"];
  };
  "/custom_object_definitions/{custom_object_definition_id}/records": {
    /** Index custom object record */
    get: operations["index_api_v1_custom_object_records"];
    /** Create custom object record */
    post: operations["create_api_v1_custom_object_records"];
  };
  "/custom_object_definitions/{id}": {
    /** Show custom object definition */
    get: operations["show_api_v1_custom_object_definitions"];
    /** Update custom object definition */
    put: operations["update_api_v1_custom_object_definitions"];
    /** Destroy custom object definition */
    delete: operations["destroy_api_v1_custom_object_definitions"];
    /** Update custom object definition */
    patch: operations["update_api_v1_custom_object_definitions"];
  };
  "/custom_object_records/{id}": {
    /** Show custom object record */
    get: operations["show_api_v1_custom_object_records"];
    /** Update custom object record */
    put: operations["update_api_v1_custom_object_records"];
    /** Destroy custom object record */
    delete: operations["destroy_api_v1_custom_object_records"];
    /** Update custom object record */
    patch: operations["update_api_v1_custom_object_records"];
  };
  "/deals": {
    /** Index deal */
    get: operations["index_api_v1_deals"];
    /** Create deal */
    post: operations["create_api_v1_deals"];
  };
  "/deals/attention": {
    /** Attention deal */
    get: operations["attention_api_v1_deals"];
  };
  "/deals/{deal_id}/tags": {
    /** Index deal tag */
    get: operations["index_api_v1_deal_tags"];
    /** Create deal tag */
    post: operations["create_api_v1_deal_tags"];
  };
  "/deals/{deal_id}/tags/{id}": {
    /** Destroy deal tag */
    delete: operations["destroy_api_v1_deal_tags"];
  };
  "/deals/{id}": {
    /** Show deal */
    get: operations["show_api_v1_deals"];
    /** Update deal */
    put: operations["update_api_v1_deals"];
    /** Destroy deal */
    delete: operations["destroy_api_v1_deals"];
    /** Update deal */
    patch: operations["update_api_v1_deals"];
  };
  "/deals/{id}/move": {
    /** Move deal */
    patch: operations["move_api_v1_deals"];
  };
  "/deals/{id}/summary": {
    /** Summary deal */
    get: operations["summary_api_v1_deals"];
  };
  "/email_sequences": {
    /** Index email sequence */
    get: operations["index_api_v1_email_sequences"];
    /** Create email sequence */
    post: operations["create_api_v1_email_sequences"];
  };
  "/email_sequences/{email_sequence_id}/enrollments": {
    /** Index sequence enrollment */
    get: operations["index_api_v1_sequence_enrollments"];
  };
  "/email_sequences/{email_sequence_id}/steps": {
    /** Index email sequence step */
    get: operations["index_api_v1_email_sequence_steps"];
    /** Create email sequence step */
    post: operations["create_api_v1_email_sequence_steps"];
  };
  "/email_sequences/{email_sequence_id}/steps/{id}": {
    /** Show email sequence step */
    get: operations["show_api_v1_email_sequence_steps"];
    /** Update email sequence step */
    put: operations["update_api_v1_email_sequence_steps"];
    /** Destroy email sequence step */
    delete: operations["destroy_api_v1_email_sequence_steps"];
    /** Update email sequence step */
    patch: operations["update_api_v1_email_sequence_steps"];
  };
  "/email_sequences/{id}": {
    /** Show email sequence */
    get: operations["show_api_v1_email_sequences"];
    /** Update email sequence */
    put: operations["update_api_v1_email_sequences"];
    /** Destroy email sequence */
    delete: operations["destroy_api_v1_email_sequences"];
    /** Update email sequence */
    patch: operations["update_api_v1_email_sequences"];
  };
  "/email_sequences/{id}/enroll": {
    /** Enroll email sequence */
    post: operations["enroll_api_v1_email_sequences"];
  };
  "/email_settings": {
    /** Show email setting */
    get: operations["show_api_v1_email_settings"];
    /** Update email setting */
    patch: operations["update_api_v1_email_settings"];
  };
  "/emails": {
    /** Index email */
    get: operations["index_api_v1_emails"];
    /** Create email */
    post: operations["create_api_v1_emails"];
  };
  "/emails/deliver": {
    /** Deliver email */
    post: operations["deliver_api_v1_emails"];
  };
  "/emails/templates": {
    /** Templates email */
    get: operations["templates_api_v1_emails"];
  };
  "/emails/{id}": {
    /** Show email */
    get: operations["show_api_v1_emails"];
    /** Update email */
    put: operations["update_api_v1_emails"];
    /** Destroy email */
    delete: operations["destroy_api_v1_emails"];
    /** Update email */
    patch: operations["update_api_v1_emails"];
  };
  "/emails/{id}/redeliver": {
    /** Redeliver email */
    post: operations["redeliver_api_v1_emails"];
  };
  "/export/csv/{type}": {
    /** Show export */
    get: operations["show_api_v1_export"];
  };
  "/import/csv": {
    /** Create import */
    post: operations["create_api_v1_import"];
  };
  "/invitations": {
    /** Index invitation */
    get: operations["index_api_v1_invitations"];
    /** Create invitation */
    post: operations["create_api_v1_invitations"];
  };
  "/invitations/{id}": {
    /** Destroy invitation */
    delete: operations["destroy_api_v1_invitations"];
  };
  "/invitations/{id}/accept": {
    /** Accept invitation */
    post: operations["accept_api_v1_invitations"];
  };
  "/memberships": {
    /** Index membership */
    get: operations["index_api_v1_memberships"];
  };
  "/memberships/{id}": {
    /** Update membership */
    put: operations["update_api_v1_memberships"];
    /** Destroy membership */
    delete: operations["destroy_api_v1_memberships"];
    /** Update membership */
    patch: operations["update_api_v1_memberships"];
  };
  "/notes": {
    /** Index note */
    get: operations["index_api_v1_notes"];
    /** Create note */
    post: operations["create_api_v1_notes"];
  };
  "/notes/{id}": {
    /** Show note */
    get: operations["show_api_v1_notes"];
    /** Update note */
    put: operations["update_api_v1_notes"];
    /** Destroy note */
    delete: operations["destroy_api_v1_notes"];
    /** Update note */
    patch: operations["update_api_v1_notes"];
  };
  "/password_resets": {
    /** Create password reset */
    post: operations["create_api_v1_password_resets"];
  };
  "/password_resets/{password_reset_id}/update": {
    /** Update password reset */
    patch: operations["update_api_v1_password_resets"];
  };
  "/pipelines": {
    /** Index pipeline */
    get: operations["index_api_v1_pipelines"];
    /** Create pipeline */
    post: operations["create_api_v1_pipelines"];
  };
  "/pipelines/{id}": {
    /** Show pipeline */
    get: operations["show_api_v1_pipelines"];
    /** Update pipeline */
    put: operations["update_api_v1_pipelines"];
    /** Destroy pipeline */
    delete: operations["destroy_api_v1_pipelines"];
    /** Update pipeline */
    patch: operations["update_api_v1_pipelines"];
  };
  "/pipelines/{pipeline_id}/stages": {
    /** Index stage */
    get: operations["index_api_v1_stages"];
    /** Create stage */
    post: operations["create_api_v1_stages"];
  };
  "/pipelines/{pipeline_id}/stages/{id}": {
    /** Show stage */
    get: operations["show_api_v1_stages"];
    /** Update stage */
    put: operations["update_api_v1_stages"];
    /** Destroy stage */
    delete: operations["destroy_api_v1_stages"];
    /** Update stage */
    patch: operations["update_api_v1_stages"];
  };
  "/plugins": {
    /** Index plugin */
    get: operations["index_api_v1_plugins"];
    /** Create plugin */
    post: operations["create_api_v1_plugins"];
  };
  "/plugins/{id}": {
    /** Show plugin */
    get: operations["show_api_v1_plugins"];
    /** Update plugin */
    put: operations["update_api_v1_plugins"];
    /** Destroy plugin */
    delete: operations["destroy_api_v1_plugins"];
    /** Update plugin */
    patch: operations["update_api_v1_plugins"];
  };
  "/sequence_enrollments/{id}": {
    /** Destroy sequence enrollment */
    delete: operations["destroy_api_v1_sequence_enrollments"];
  };
  "/sequence_enrollments/{id}/unsubscribe": {
    /** Unsubscribe sequence enrollment */
    post: operations["unsubscribe_api_v1_sequence_enrollments"];
  };
  "/tags": {
    /** Index tag */
    get: operations["index_api_v1_tags"];
    /** Create tag */
    post: operations["create_api_v1_tags"];
  };
  "/tags/{id}": {
    /** Destroy tag */
    delete: operations["destroy_api_v1_tags"];
  };
  "/unsubscribe": {
    /** Create unsubscribe */
    post: operations["create_api_v1_unsubscribes"];
  };
  "/users/me": {
    /** Update current user (name, password, first-login setup) */
    patch: operations["me_api_v1_users"];
  };
  "/webhooks": {
    /** Index webhook */
    get: operations["index_api_v1_webhooks"];
    /** Create webhook */
    post: operations["create_api_v1_webhooks"];
  };
  "/webhooks/resend/{account_id}": {
    /** Create resend webhook */
    post: operations["create_api_v1_resend_webhooks"];
  };
  "/webhooks/{id}": {
    /** Show webhook */
    get: operations["show_api_v1_webhooks"];
    /** Update webhook */
    put: operations["update_api_v1_webhooks"];
    /** Destroy webhook */
    delete: operations["destroy_api_v1_webhooks"];
    /** Update webhook */
    patch: operations["update_api_v1_webhooks"];
  };
  "/webhooks/{id}/deliveries": {
    /** Deliveries webhook */
    get: operations["deliveries_api_v1_webhooks"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Index activity */
  index_api_v1_activities: {
    parameters: {
      query?: {
        q?: string;
        page?: number;
        per_page?: number;
        kind?: string;
        assignee_id?: string;
        completed?: string;
        overdue?: string;
        due_from?: string;
        due_to?: string;
        sort?: string;
        order?: string;
        direction?: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Create activity */
  create_api_v1_activities: {
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Show activity */
  show_api_v1_activities: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Update activity */
  update_api_v1_activities: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Destroy activity */
  destroy_api_v1_activities: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Settings ai */
  settings_api_v1_ai: {
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Update settings ai */
  update_settings_api_v1_ai: {
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Test connection ai */
  test_connection_api_v1_ai: {
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Index api token */
  index_api_v1_api_tokens: {
    parameters: {
      query?: {
        q?: string;
        page?: number;
        per_page?: number;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Create api token */
  create_api_v1_api_tokens: {
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Destroy api token */
  destroy_api_v1_api_tokens: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Log in and receive a session token */
  login_api_v1_auth: {
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Revoke the current session */
  logout_api_v1_auth: {
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Current user, account and memberships */
  me_api_v1_auth: {
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Providers auth */
  providers_api_v1_auth: {
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Sign up with email, password and workspace name */
  signup_api_v1_auth: {
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Switch the session's current workspace */
  switch_account_api_v1_auth: {
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Index automation */
  index_api_v1_automations: {
    parameters: {
      query?: {
        q?: string;
        page?: number;
        per_page?: number;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Create automation */
  create_api_v1_automations: {
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Templates automation */
  templates_api_v1_automations: {
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Show automation */
  show_api_v1_automations: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Update automation */
  update_api_v1_automations: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Destroy automation */
  destroy_api_v1_automations: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Runs automation */
  runs_api_v1_automations: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Toggle automation */
  toggle_api_v1_automations: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Index company */
  index_api_v1_companies: {
    parameters: {
      query?: {
        q?: string;
        page?: number;
        per_page?: number;
        sort?: string;
        direction?: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Create company */
  create_api_v1_companies: {
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Index company tag */
  index_api_v1_company_tags: {
    parameters: {
      query?: {
        q?: string;
        page?: number;
        per_page?: number;
      };
      path: {
        company_id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Create company tag */
  create_api_v1_company_tags: {
    parameters: {
      path: {
        company_id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Destroy company tag */
  destroy_api_v1_company_tags: {
    parameters: {
      path: {
        company_id: string;
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Show company */
  show_api_v1_companies: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Update company */
  update_api_v1_companies: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Destroy company */
  destroy_api_v1_companies: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Index contact */
  index_api_v1_contacts: {
    parameters: {
      query?: {
        q?: string;
        page?: number;
        per_page?: number;
        status?: string;
        tag_id?: string;
        sort?: string;
        direction?: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Create contact */
  create_api_v1_contacts: {
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Import contact */
  import_api_v1_contacts: {
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Index contact tag */
  index_api_v1_contact_tags: {
    parameters: {
      query?: {
        q?: string;
        page?: number;
        per_page?: number;
      };
      path: {
        contact_id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Create contact tag */
  create_api_v1_contact_tags: {
    parameters: {
      path: {
        contact_id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Destroy contact tag */
  destroy_api_v1_contact_tags: {
    parameters: {
      path: {
        contact_id: string;
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Show contact */
  show_api_v1_contacts: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Update contact */
  update_api_v1_contacts: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Destroy contact */
  destroy_api_v1_contacts: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Erase contact */
  erase_api_v1_contacts: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Export contact */
  export_api_v1_contacts: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Score contact */
  score_api_v1_contacts: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Index custom field definition */
  index_api_v1_custom_field_definitions: {
    parameters: {
      query?: {
        q?: string;
        page?: number;
        per_page?: number;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Create custom field definition */
  create_api_v1_custom_field_definitions: {
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Show custom field definition */
  show_api_v1_custom_field_definitions: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Update custom field definition */
  update_api_v1_custom_field_definitions: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Destroy custom field definition */
  destroy_api_v1_custom_field_definitions: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Index custom object definition */
  index_api_v1_custom_object_definitions: {
    parameters: {
      query?: {
        q?: string;
        page?: number;
        per_page?: number;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Create custom object definition */
  create_api_v1_custom_object_definitions: {
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Index custom object record */
  index_api_v1_custom_object_records: {
    parameters: {
      query?: {
        q?: string;
        page?: number;
        per_page?: number;
      };
      path: {
        custom_object_definition_id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Create custom object record */
  create_api_v1_custom_object_records: {
    parameters: {
      path: {
        custom_object_definition_id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Show custom object definition */
  show_api_v1_custom_object_definitions: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Update custom object definition */
  update_api_v1_custom_object_definitions: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Destroy custom object definition */
  destroy_api_v1_custom_object_definitions: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Show custom object record */
  show_api_v1_custom_object_records: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Update custom object record */
  update_api_v1_custom_object_records: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Destroy custom object record */
  destroy_api_v1_custom_object_records: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Index deal */
  index_api_v1_deals: {
    parameters: {
      query?: {
        q?: string;
        page?: number;
        per_page?: number;
        pipeline_id?: string;
        tag_id?: string;
        sort?: string;
        direction?: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Create deal */
  create_api_v1_deals: {
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Attention deal */
  attention_api_v1_deals: {
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Index deal tag */
  index_api_v1_deal_tags: {
    parameters: {
      query?: {
        q?: string;
        page?: number;
        per_page?: number;
      };
      path: {
        deal_id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Create deal tag */
  create_api_v1_deal_tags: {
    parameters: {
      path: {
        deal_id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Destroy deal tag */
  destroy_api_v1_deal_tags: {
    parameters: {
      path: {
        deal_id: string;
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Show deal */
  show_api_v1_deals: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Update deal */
  update_api_v1_deals: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Destroy deal */
  destroy_api_v1_deals: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Move deal */
  move_api_v1_deals: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Summary deal */
  summary_api_v1_deals: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Index email sequence */
  index_api_v1_email_sequences: {
    parameters: {
      query?: {
        q?: string;
        page?: number;
        per_page?: number;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Create email sequence */
  create_api_v1_email_sequences: {
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Index sequence enrollment */
  index_api_v1_sequence_enrollments: {
    parameters: {
      query?: {
        q?: string;
        page?: number;
        per_page?: number;
      };
      path: {
        email_sequence_id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Index email sequence step */
  index_api_v1_email_sequence_steps: {
    parameters: {
      query?: {
        q?: string;
        page?: number;
        per_page?: number;
      };
      path: {
        email_sequence_id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Create email sequence step */
  create_api_v1_email_sequence_steps: {
    parameters: {
      path: {
        email_sequence_id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Show email sequence step */
  show_api_v1_email_sequence_steps: {
    parameters: {
      path: {
        email_sequence_id: string;
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Update email sequence step */
  update_api_v1_email_sequence_steps: {
    parameters: {
      path: {
        email_sequence_id: string;
        id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Destroy email sequence step */
  destroy_api_v1_email_sequence_steps: {
    parameters: {
      path: {
        email_sequence_id: string;
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Show email sequence */
  show_api_v1_email_sequences: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Update email sequence */
  update_api_v1_email_sequences: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Destroy email sequence */
  destroy_api_v1_email_sequences: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Enroll email sequence */
  enroll_api_v1_email_sequences: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Show email setting */
  show_api_v1_email_settings: {
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Update email setting */
  update_api_v1_email_settings: {
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Index email */
  index_api_v1_emails: {
    parameters: {
      query?: {
        q?: string;
        page?: number;
        per_page?: number;
        contact_id?: string;
        deal_id?: string;
        status?: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Create email */
  create_api_v1_emails: {
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Deliver email */
  deliver_api_v1_emails: {
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Templates email */
  templates_api_v1_emails: {
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Show email */
  show_api_v1_emails: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Update email */
  update_api_v1_emails: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Destroy email */
  destroy_api_v1_emails: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Redeliver email */
  redeliver_api_v1_emails: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Show export */
  show_api_v1_export: {
    parameters: {
      path: {
        type: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Create import */
  create_api_v1_import: {
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Index invitation */
  index_api_v1_invitations: {
    parameters: {
      query?: {
        q?: string;
        page?: number;
        per_page?: number;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Create invitation */
  create_api_v1_invitations: {
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Destroy invitation */
  destroy_api_v1_invitations: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Accept invitation */
  accept_api_v1_invitations: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Index membership */
  index_api_v1_memberships: {
    parameters: {
      query?: {
        q?: string;
        page?: number;
        per_page?: number;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Update membership */
  update_api_v1_memberships: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Destroy membership */
  destroy_api_v1_memberships: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Index note */
  index_api_v1_notes: {
    parameters: {
      query?: {
        q?: string;
        page?: number;
        per_page?: number;
        notable_type?: string;
        notable_id?: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Create note */
  create_api_v1_notes: {
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Show note */
  show_api_v1_notes: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Update note */
  update_api_v1_notes: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Destroy note */
  destroy_api_v1_notes: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Create password reset */
  create_api_v1_password_resets: {
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Update password reset */
  update_api_v1_password_resets: {
    parameters: {
      path: {
        password_reset_id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Index pipeline */
  index_api_v1_pipelines: {
    parameters: {
      query?: {
        q?: string;
        page?: number;
        per_page?: number;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Create pipeline */
  create_api_v1_pipelines: {
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Show pipeline */
  show_api_v1_pipelines: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Update pipeline */
  update_api_v1_pipelines: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Destroy pipeline */
  destroy_api_v1_pipelines: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Index stage */
  index_api_v1_stages: {
    parameters: {
      query?: {
        q?: string;
        page?: number;
        per_page?: number;
      };
      path: {
        pipeline_id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Create stage */
  create_api_v1_stages: {
    parameters: {
      path: {
        pipeline_id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Show stage */
  show_api_v1_stages: {
    parameters: {
      path: {
        pipeline_id: string;
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Update stage */
  update_api_v1_stages: {
    parameters: {
      path: {
        pipeline_id: string;
        id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Destroy stage */
  destroy_api_v1_stages: {
    parameters: {
      path: {
        pipeline_id: string;
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Index plugin */
  index_api_v1_plugins: {
    parameters: {
      query?: {
        q?: string;
        page?: number;
        per_page?: number;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Create plugin */
  create_api_v1_plugins: {
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Show plugin */
  show_api_v1_plugins: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Update plugin */
  update_api_v1_plugins: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Destroy plugin */
  destroy_api_v1_plugins: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Destroy sequence enrollment */
  destroy_api_v1_sequence_enrollments: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Unsubscribe sequence enrollment */
  unsubscribe_api_v1_sequence_enrollments: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Index tag */
  index_api_v1_tags: {
    parameters: {
      query?: {
        q?: string;
        page?: number;
        per_page?: number;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Create tag */
  create_api_v1_tags: {
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Destroy tag */
  destroy_api_v1_tags: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Create unsubscribe */
  create_api_v1_unsubscribes: {
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Update current user (name, password, first-login setup) */
  me_api_v1_users: {
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Index webhook */
  index_api_v1_webhooks: {
    parameters: {
      query?: {
        q?: string;
        page?: number;
        per_page?: number;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Create webhook */
  create_api_v1_webhooks: {
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Create resend webhook */
  create_api_v1_resend_webhooks: {
    parameters: {
      path: {
        account_id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      201: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Show webhook */
  show_api_v1_webhooks: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Update webhook */
  update_api_v1_webhooks: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Destroy webhook */
  destroy_api_v1_webhooks: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
  /** Deliveries webhook */
  deliveries_api_v1_webhooks: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Missing or invalid token */
      401: {
        content: never;
      };
    };
  };
}
