AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - "db/schema.rb"
    - "bin/**/*"
    - "vendor/**/*"

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Layout/LineLength:
  Max: 120
